"""
export_weights.py  –  Export PyTorch Policy to C++ Header
==========================================================
Reads a trained PPO model + VecNormalize statistics and writes
firmware/model_weights.h, which is #included by the Teensy firmware
and loaded into RAM via init_ram_weights() at boot.

Usage:
    python scripts/export_weights.py
"""
import os
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

from envs import PhysicalFurutaEnv

# ------------------------------------------------------------------ #
#  Configuration – point these at your final model                   #
# ------------------------------------------------------------------ #
SERIAL_PORT   = "COM3"   # only needed to construct PhysicalFurutaEnv for the dummy env
MODEL_PATH    = "./saved_models/PPO_dynfric_dyngrav_3000_alpha03_08/best_model.zip"
VEC_NORM_PATH = "./saved_models/PPO_dynfric_dyngrav_3000_alpha03_08/best_vec_normalize.pkl"
OUTPUT_FILE   = "./firmware/model_weights.h"


def write_1d(f, name: str, arr: np.ndarray):
    f.write(f"const float {name}[{len(arr)}] = {{\n")
    f.write("  " + ", ".join(f"{v:.6f}" for v in arr) + "\n")
    f.write("};\n\n")


def write_2d(f, name: str, arr: np.ndarray):
    rows, cols = arr.shape
    f.write(f"const float {name}[{rows}][{cols}] = {{\n")
    for i, row in enumerate(arr):
        suffix = "," if i < rows - 1 else ""
        f.write("  {" + ", ".join(f"{v:.6f}" for v in row) + "}" + suffix + "\n")
    f.write("};\n\n")


def main():
    print(f"[*] Loading model from: {MODEL_PATH}")

    # Load VecNormalize to extract obs mean / variance
    dummy_env = DummyVecEnv([lambda: PhysicalFurutaEnv(SERIAL_PORT)])
    vec_env   = VecNormalize.load(VEC_NORM_PATH, dummy_env)
    obs_mean  = vec_env.obs_rms.mean
    obs_var   = vec_env.obs_rms.var

    # Load policy weights
    model  = PPO.load(MODEL_PATH)
    params = model.policy.state_dict()

    w1 = params["mlp_extractor.policy_net.0.weight"].cpu().numpy()
    b1 = params["mlp_extractor.policy_net.0.bias"].cpu().numpy()
    w2 = params["mlp_extractor.policy_net.2.weight"].cpu().numpy()
    b2 = params["mlp_extractor.policy_net.2.bias"].cpu().numpy()
    w3 = params["action_net.weight"].cpu().numpy()
    b3 = params["action_net.bias"].cpu().numpy()

    print(f"[*] Writing {OUTPUT_FILE}...")
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("#ifndef MODEL_WEIGHTS_H\n#define MODEL_WEIGHTS_H\n\n")
        f.write("// Auto-generated by scripts/export_weights.py – do not edit manually.\n")
        f.write("// MLP architecture: 6 → 64 → 64 → 1  (tanh activations, linear output)\n\n")

        write_1d(f, "obs_mean", obs_mean)
        write_1d(f, "obs_var",  obs_var)
        write_2d(f, "W1", w1)
        write_1d(f, "b1", b1)
        write_2d(f, "W2", w2)
        write_1d(f, "b2", b2)
        write_2d(f, "W3", w3)
        write_1d(f, "b3", b3)

        f.write("#endif // MODEL_WEIGHTS_H\n")

    print(f"[OK] {OUTPUT_FILE} written successfully.")
    dummy_env.close()


if __name__ == "__main__":
    main()
